const ResumeApi = [
  {
    id: 1,
    category: "education",
    year: "(2012)",
    title: "SDN 1 Klapasawit",
    desc: "Elementary School",
    rate: "UN : 27,3",
  },
  {
    id: 2,
    category: "education",
    year: "(2016)",
    title: "SMP N 1 Kebumen ",
    desc: "Junior High School",
    rate: "UN : 37,1",
  },
  {
    id: 3,
    category: "education",
    year: "(2019)",
    title: "SMA N 1 Kebumen",
    desc: "Senior High School",
    rate: "UN : 37,1",
  },
  {
    id: 4,
    category: "education",
    year: "(Current)",
    title: "Institut Teknologi Bandung",
    desc: "University",
    rate: "IPK : 3.45",
  },
  {
    id: 5,
    category: "education",
    year: "(Current)",
    title: "Bangkit Academy",
    desc: "Program Certification for Android Development Google",
    rate: "Not Yet",
  },
  {
    id: 6,
    category: "experience",
    year: "June 2021",
    title: "PT Cryptoscope (Ctscope)",
    desc: "React Developer",
    rate: "Internship",
  },
  {
    id: 7,
    category: "experience",
    year: "August 2021",
    title: "MAN IC OKI",
    desc: "Frontend Developer, Project Manager",
    rate: "Freelancing",
  },
  {
    id: 8,
    category: "experience",
    year: "Desember 2021",
    title: "Maximus Assurance",
    desc: "Frontend Developer",
    rate: "Freelancing",
  },
  {
    id: 9,
    category: "experience",
    year: "August 2021 - Current",
    title: "Helper | Teman Setia Anak Rantau",
    desc: "Founder and CEO",
    rate: "Startup",
  },
  {
    id: 10,
    category: "experience",
    year: "January 2022",
    title: "Linkn",
    desc: "Frontend Developer",
    rate: "Freelancing",
  },
  {
    id: 10,
    category: "experience",
    year: "Mei 2022",
    title: "OneTap.In",
    desc: "UI UX Designer",
    rate: "Freelance",
  },
  {
    id: 10,
    category: "experience",
    year: "Mei 2022",
    title: "ParaCare",
    desc: "UI UX Designer",
    rate: "Freelance",
  },
  {
    id: 10,
    category: "experience",
    year: "Mei 2022",
    title: "Design Maker",
    desc: "UI UX Designer",
    rate: "Freelance",
  },
  {
    id: 10,
    category: "experience",
    year: "Mei 2022",
    title: "Sidhutaguna",
    desc: "UI UX Designer",
    rate: "Freelance",
  },
  {
    id: 10,
    category: "experience",
    year: "Juni 2022",
    title: "Paragon Technology and Innovation",
    desc: "Android Developer",
    rate: "Intership",
  },
]

export default ResumeApi
