const Portfolio_data = [
  {
    category: "Frotend Developer",
    date: "11 April 2021",
    title: "Search Engine",
    image: "./image/porto11.png",
    desc : "Website ini adalah tugas perkuliahan Aljabar dan Geometri. Program mampu bertindak sebagai search engine dengan menggunakan algoritm Cosine Similiarty. Website mampu menerima inputan dari user kemudian mencari seperti halnya Google",
    link : "https://github.com/tararahuuw/Algeo02-19077",
  },
  {
    category: "Frotend Developer",
    date: "29 April 2021",
    title: "Chatbot Website",
    image: "./image/porto21.png",
    desc : "Website ini adalah tugas perkuliahan strategi algoritma. Program mampu bertindak sebagai chatbot dengan mengginakan algoritm string matching. Website mampu menerima inputan dari user kemudian dapat menjawab pertanyaan dari user",
    link : "https://github.com/tararahuuw/Deadline-Tubes.git",
  },
  {
    category: "Frotend Developer",
    date: "1 Juni 2021",
    title: "PT Crytoscope",
    image: "./image/porto31.png",
    desc : "Website ini adalah landing page dari perusahaan Ctscope. Project ini dikerjakan untuk memenuhi tugas internship. Project ini menggunakan technologi react js",
    link : "https://ctscope.io/",
  },
  {
    category: "Frotend Developer",
    date: "10 Juni 2021",
    title: "Chinese Remainder Problem Calculator",
    image: "./image/porto41.png",
    desc : "Website ini adalah tugas perkuliahan strategi algoritma. Program mampu bertindak sebagai calculator dengan menggunakan algoritm chinese remainder problem. Website mampu menerima inputan dari user kemudian menghitung solusi permasalahan CRT",
    link : "https://ctscope.io/",
  },
  {
    category: "Machine Learning",
    date: "10 Juni 2021",
    title: "Pengolahan Citra Image",
    image: "./image/porto51.png",
    desc : "Website ini adalah tugas perkuliahan strategi algoritma. Program mampu bertindak compressor foto dengan menggunakan algoritma Kode Huffman. Program mampu menerima inputan dari user berupa foto kemudian mengkompresnya menjadi ukuran yang lebih kecil namun mengurangi resolusi fotonya",
    link : "https://ctscope.io/",
  },
  {
    category: "Project Manager, Frontend Developer",
    date: "Agustus 2021",
    title: "Website Learning MAN IC Lampung",
    image: "./image/porto61.png",
    desc : "Website ini adalah hasil project Man IC Lampung. Project ini bertujuan untuk membuat website learning untuk para siswa man untuk mengupload setoran hafalan Al-quran mereka",
    link : "https://e-tahfidz.insancendekia-oki.com/",
  },
  {
    category: "UI UX Designer",
    date: "23 November 2021",
    title: "ReTreeat App",
    image: "./image/porto81.png",
    desc : "Design ini adalah tugas perkuliahan interaksi manusia dan komputer. Design ini bertujuan untuk mendesign sebuah aplikasi yang dapat menerima sebuah donasi untuk kebutuhan reboisasi hutan.",
    link : "https://www.figma.com/file/JEVbiKGLOmbFXHv33to9jR/IMK-C1?node-id=68%3A2",
  },
  {
    category: "Frontend Developer",
    date: "Januari 2022",
    title: "Maximus Assurance",
    image: "./image/porto91.png",
    desc : "Website ini adalah hasil project PT Assurance Maximus. Project ini bertujuan untuk membuat website asuransi otomatis",
    link : "https://www.asuransimaximus.com/index.php/en/",
  },
  {
    category: "Fullstack Developer",
    date: "24 Januari 2022",
    title: "E-Commerce Dorayaki Store",
    image: "./image/porto131.png",
    desc : "Website ini adalah tugas perkuliahan website. Website ini bertindak sebagai e-commerce untuk penjualan dorayaki",
    link : "https://github.com/tararahuuw/E-Commerce-Dorayaki.git",
  },
  {
    category: "Android Developer",
    date: "5 Maret 2022",
    title: "Peduli Lindungi Cloning App",
    image: "./image/porto111.png",
    desc : "Aplikasi ini adalah tugas perkuliahan android. Aplikasi ini mampu untuk menscan barcode untuk mengecek status vaksinasi user",
    link : "https://github.com/tararahuuw/Aplikasi-Vaksinasi.git",
  },
  {
    category: "WebGl Developer",
    date: "23 Maret 2022",
    title: "Blender Cloning App",
    image: "./image/porto121.png",
    desc : "Website ini adalah tugas perkuliahan grafika komputer. Website ini mampu untuk membuat bangun dalam 3 dimensi",
    link : "https://github.com/tararahuuw/Blender-Cloning-Webgl.git",
  },
  {
    category: "Android Developer",
    date: "29 Maret 2022",
    title: "Github User App",
    image: "./image/porto141.png",
    desc : "Website ini adalah tugas perkuliahan website. Website ini bertindak sebagai e-commerce untuk penjualan dorayaki",
    link : "https://github.com/tararahuuw/Dicoding-Fundamental-Android.git",
  },
  {
    category: "Frontend Developer",
    date: "April 2022",
    title: "Linkn Website",
    image: "./image/porto101.png",
    desc : "Website ini adalah tugas perkuliahan proyek perangkat lunak. Website ini mampu untuk menyimpan beberapa link user ke dalam sebuah interaktif website",
    link : "https://www.asuransimaximus.com/index.php/en/",
  },
  {
    category: "Founder & CEO",
    date: "2021 - Current",
    title: "Helper Super App",
    image: "./image/porto151.png",
    desc : "Super App Penyedia Kebutuhan Anak Rantau Hadir sebagai teman setia anak-anak rantau di Indonesia. Helper membantu Anda menyediakan makanan catering, pencarian tempat tinggal, dan penyedia peralatan rumah tangga.",
    link : "https://helperindonesia.com/",
  },
]
export default Portfolio_data
