const Portfolio_data = [
  {
    category: "Frotend Developer",
    date: "11 April 2021",
    title: "Search Engine",
    image: "./image/porto1.png",
    desc : "Website ini adalah tugas perkuliahan Aljabar dan Geometri. Program mampu bertindak sebagai search engine dengan menggunakan algoritm Cosine Similiarty. Website mampu menerima inputan dari user kemudian mencari seperti halnya Google",
    link : "https://github.com/tararahuuw/Algeo02-19077",
  },
  {
    category: "Machine Learning",
    date: "20 April 2021",
    title: "JARVIS Personal Assistant",
    image: "./image/porto29.png",
    desc : "Program JARVIS berguna untuk menjadi private personal assitant desktop",
    link : "https://github.com/tararahuuw/J.A.R.V.I.S-Assistant",
  },
  {
    category: "Frotend Developer",
    date: "29 April 2021",
    title: "Chatbot Website",
    image: "./image/porto2.png",
    desc : "Website ini adalah tugas perkuliahan strategi algoritma. Program mampu bertindak sebagai chatbot dengan mengginakan algoritm string matching. Website mampu menerima inputan dari user kemudian dapat menjawab pertanyaan dari user",
    link : "https://github.com/tararahuuw/Deadline-Tubes.git",
  },
  {
    category: "Frotend Developer",
    date: "1 Juni 2021",
    title: "PT Crytoscope",
    image: "./image/porto3.png",
    desc : "Website ini adalah landing page dari perusahaan Ctscope. Project ini dikerjakan untuk memenuhi tugas internship. Project ini menggunakan technologi react js",
    link : "https://ctscope.io/",
  },
  {
    category: "Frotend Developer",
    date: "10 Juni 2021",
    title: "Chinese Remainder Problem Calculator",
    image: "./image/porto4.png",
    desc : "Website ini adalah tugas perkuliahan strategi algoritma. Program mampu bertindak sebagai calculator dengan menggunakan algoritm chinese remainder problem. Website mampu menerima inputan dari user kemudian menghitung solusi permasalahan CRT",
    link : "https://ctscope.io/",
  },
  {
    category: "Machine Learning",
    date: "10 Juni 2021",
    title: "Pengolahan Citra Image",
    image: "./image/porto5.png",
    desc : "Website ini adalah tugas perkuliahan strategi algoritma. Program mampu bertindak compressor foto dengan menggunakan algoritma Kode Huffman. Program mampu menerima inputan dari user berupa foto kemudian mengkompresnya menjadi ukuran yang lebih kecil namun mengurangi resolusi fotonya",
    link : "https://ctscope.io/",
  },
  {
    category: "Machine Learning, Frontend Developer",
    date: "Juli 2021",
    title: "Path Finder Website",
    image: "./image/porto30.png",
    desc : "Website ini adalah tugas mata kuliah STIMA. Website ini bertujuan untuk mencari jalan terdekat untuk menuju suatu lokasi",
    link : "https://github.com/widyaput/Tucil3STIMA",
  },
  {
    category: "Game Developer",
    date: "20 Juli 2021",
    title: "Worms War Game",
    image: "./image/porto31.png",
    desc : "Game ini adalah tugas mata kuliah STIMA. Game ini bertujuan untuk melakukan team battle antara 2 team dengan player berupa cacing yang dilengkapi senjata",
    link : "https://github.com/tararahuuw/Tubes-STIMA-2",
  },
  {
    category: "Game Developer",
    date: "29 Juli 2021",
    title: "Pokemon Game",
    image: "./image/porto32.png",
    desc : "Game ini adalah tugas mata kuliah OOP. Game ini bertujuan untuk melakukan petualangan dan eksplorasi pada dunia Pokemon",
    link : "https://github.com/tararahuuw/Tubes-STIMA-2",
  },
  {
    category: "Project Manager, Frontend Developer",
    date: "Agustus 2021",
    title: "Website Learning MAN IC Lampung",
    image: "./image/porto6.png",
    desc : "Website ini adalah hasil project Man IC Lampung. Project ini bertujuan untuk membuat website learning untuk para siswa man untuk mengupload setoran hafalan Al-quran mereka",
    link : "https://e-tahfidz.insancendekia-oki.com/",
  },
  {
    category: "UI UX Designer",
    date: "23 November 2021",
    title: "ReTreeat App",
    image: "./image/porto8.png",
    desc : "Design ini adalah tugas perkuliahan interaksi manusia dan komputer. Design ini bertujuan untuk mendesign sebuah aplikasi yang dapat menerima sebuah donasi untuk kebutuhan reboisasi hutan.",
    link : "https://www.figma.com/file/JEVbiKGLOmbFXHv33to9jR/IMK-C1?node-id=68%3A2",
  },
  {
    category: "Frontend Developer",
    date: "Januari 2022",
    title: "Maximus Assurance",
    image: "./image/porto9.png",
    desc : "Website ini adalah hasil project PT Assurance Maximus. Project ini bertujuan untuk membuat website asuransi otomatis",
    link : "https://www.asuransimaximus.com/index.php/en/",
  },
  {
    category: "Fullstack Developer",
    date: "24 Januari 2022",
    title: "E-Commerce Dorayaki Store",
    image: "./image/porto13.png",
    desc : "Website ini adalah tugas perkuliahan website. Website ini bertindak sebagai e-commerce untuk penjualan dorayaki",
    link : "https://github.com/tararahuuw/E-Commerce-Dorayaki.git",
  },
  {
    category: "Machine Learning",
    date: "1 Februari 2022",
    title: "Connect Four Board Game",
    image: "./image/porto22.png",
    desc : "Program ini adalah tugas perkuliahan artificial intelligent. Program ini bertujuan untuk membuat bot yang mampu menggunakan algoritma local search",
    link : "https://gitlab.informatika.org/widyaput/simplexity-ai",
  },
  {
    category: "Jaringan Komputer",
    date: "15 Februari 2022",
    title: "TCP VS UDP Program",
    image: "./image/porto23.png",
    desc : "Program ini adalah tugas perkuliahan jaringan komputer. Program ini bertujuan untuk membuat platform bertukar data dengan tcp dan udp",
    link : "https://gitlab.informatika.org/widyaput/tcp-over-udp",
  },
  {
    category: "Webgl Developer",
    date: "1 Maret 2022",
    title: "Paint Drawing Website",
    image: "./image/porto17.png",
    desc : "Website ini adalah tugas perkuliahan grafika komputer. Website ini mampu menggambar objek sama seperti paint drawing",
    link : "https://docs.google.com/document/d/1Z9YtyWiB9137-qsf2ldGJOjFOlF_YU_XZbXANLPaSp8/edit#",
  },
  {
    category: "Android Developer",
    date: "5 Maret 2022",
    title: "Peduli Lindungi Cloning App",
    image: "./image/porto11.png",
    desc : "Aplikasi ini adalah tugas perkuliahan android. Aplikasi ini mampu untuk menscan barcode untuk mengecek status vaksinasi user",
    link : "https://github.com/tararahuuw/Aplikasi-Vaksinasi.git",
  },
  {
    category: "WebGl Developer",
    date: "23 Maret 2022",
    title: "3D Game Object",
    image: "./image/porto12.png",
    desc : "Website ini adalah tugas perkuliahan grafika komputer. Website ini mampu untuk membuat bangun dalam 3 dimensi",
    link : "https://github.com/tararahuuw/Blender-Cloning-Webgl.git",
  },
  {
    category: "Sistem Terdistribusi",
    date: "15 Maret 2022",
    title: "Cross Matrix OpenMPI",
    image: "./image/porto19.png",
    desc : "Program ini adalah tugas perkuliahan sistem terdistribusi. Program ini mampu memecahkan perkalian matriks dimensi tinggi dengan menggunakan OpenMPI",
    link : "https://gitlab.informatika.org/Alamsyah/if3230-2022-k02-11",
  },
  {
    category: "Android Developer",
    date: "25 Maret 2022",
    title: "Github User App",
    image: "./image/porto14.png",
    desc : "Aplikasi ini adalah tugas sertifikasi fundamental android.",
    link : "https://github.com/tararahuuw/Dicoding-Fundamental-Android.git",
  },
  {
    category: "Sistem Terdistribusi",
    date: "29 Maret 2022",
    title: "CUDA NVIDIA",
    image: "./image/porto20.png",
    desc : "Program ini adalah tugas perkuliahan sistem terdistribusi. Program ini mampu memecahkan perkalian matriks dimensi tinggi dengan menggunakan CUDA",
    link : "https://gitlab.informatika.org/thomas-fm/if3230-2022-k02-11-tb2",
  },
  {
    category: "Frontend Developer",
    date: "April 2022",
    title: "Linkn Website",
    image: "./image/porto10.png",
    desc : "Website ini adalah tugas perkuliahan proyek perangkat lunak. Website ini mampu untuk menyimpan beberapa link user ke dalam sebuah interaktif website",
    link : "https://www.asuransimaximus.com/index.php/en/",
  },
  {
    category: "Founder & CEO",
    date: "2021 - Current",
    title: "Helper Super App",
    image: "./image/porto15.png",
    desc : "Super App Penyedia Kebutuhan Anak Rantau Hadir sebagai teman setia anak-anak rantau di Indonesia. Helper membantu Anda menyediakan makanan catering, pencarian tempat tinggal, dan penyedia peralatan rumah tangga.",
    link : "https://helperindonesia.com/",
  },
  {
    category: "Game Developer",
    date: "April 2022",
    title: "Survival Shooter",
    image: "./image/porto18.png",
    desc : "Game ini adalah tugas perkuliahan PBD. Tujuan dari game ini adalah mengumpulkan point sebanyak-banyaknya dengan membunuh zombie yang ada",
    link : "https://gitlab.informatika.org/Alamsyah/if3210-2022-unity-46/-/tree/branch-final",
  },
  {
    category: "Sistem Paralel",
    date: "April 2022",
    title: "Paxos and Raft",
    image: "./image/porto21.png",
    desc : "Program ini adalah tugas perkuliahan sistem terdistribusi. Program ini mampu memecahkan permasalahan mengenai decentralized consensus.",
    link : "https://gitlab.informatika.org/thomas-fm/if3230-2022-k02-11-tb2",
  },
  {
    category: "Webgl Developer",
    date: "April 2022",
    title: "3D Blender Object",
    image: "./image/porto16.png",
    desc : "Tugas website ini untuk membuat 3D blender app dalam sebuah website",
    link : "https://docs.google.com/document/d/1mYrx43TIfd9Eg6A--e9T3JIXNzrDYCWLoO4keuASLGo/edit#",
  },
  {
    category: "UI UX Designer",
    date: "25 Mei 2022",
    title: "OneTap.In",
    image: "./image/porto25.png",
    desc : "Freelance design UI UX untuk mahasiswa elektro ITB",
    link : "https://www.figma.com/proto/F6zAuW8k1Tq40PPeSopRws/Integration-system-mobile?node-id=3%3A12&starting-point-node-id=3%3A12&scaling=scale-down",
  },
  {
    category: "UI UX Designer",
    date: "25 Mei 2022",
    title: "ParaCare",
    image: "./image/porto26.png",
    desc : "Freelance design UI UX untuk mahasiswa elektro ITB",
    link : "https://www.figma.com/proto/YFkhLaZpIkZ6MjIBBiUXWL/Beauty-Clinic-Skincare-App-(Community)?node-id=856%3A1306&starting-point-node-id=856%3A1306&scaling=scale-down",
  },
  {
    category: "UI UX Designer",
    date: "25 Mei 2022",
    title: "Design Maker",
    image: "./image/porto27.png",
    desc : "Freelance design UI UX untuk mahasiswa elektro ITB",
    link : "https://www.figma.com/proto/DfEotGjOG2JPojZrNsweu0/Ojan-punya?node-id=2%3A16&starting-point-node-id=2%3A16&scaling=scale-down",
  },
  {
    category: "Android Developer",
    date: "1 Juni 2022",
    title: "Paragon Technology and Innovation",
    image: "./image/porto24.png",
    desc : "Internship sebagai mobile developer di Paragon Technology and Innovation",
    link : "https://www.paragon-innovation.com/",
  },
  {
    category: "UI UX Designer",
    date: "4 Juni 2022",
    title: "Sidhutaguna",
    image: "./image/porto28.png",
    desc : "Freelance design UI UX untuk mahasiswa bisnis ITS",
    link : "https://www.figma.com/proto/EHr0jtCbF9ajx0z3VTWdfR/Sidhutaguna?node-id=2%3A3&starting-point-node-id=2%3A3&scaling=scale-down",
  },
  
]
export default Portfolio_data
