const BlogApi = [
  {
    id: 1,
    image: "./image/1-1.png",
    date: "20 February, 2022",
    image1: "./image/1-2.png",
    image2: "./image/1-3.png",
    title_one: "Memulai Pemrograman Dengan Kotlin",
    desc_one: "Dicoding Certification",
  },
  {
    id: 2,
    image: "./image/2-1.png",
    date: "26 March, 2022",
    image1: "./image/2-2.png",
    image2: "./image/2-3.png",
    title_one: "Belajar Fundamental Aplikasi Android",
    desc_one: "Dicoding Certification",
  },
  {
    id: 2,
    image: "./image/3-1.png",
    date: "31 March, 2022",
    image1: "./image/3-2.png",
    image2: "",
    title_one: "Belajar Prinsip Pemrograman SOLID",
    desc_one: "Dicoding Certification",
  },
  {
    id: 2,
    image: "./image/4-1.png",
    date: "28 April, 2022",
    image1: "./image/4-2.png",
    image2: "./image/4-3.png",
    title_one: "Belajar Dasar UX Design",
    desc_one: "Dicoding Certification",
  },
  {
    id: 2,
    image: "./image/5-1.png",
    date: "9 Mei, 2022",
    image1: "./image/5-2.png",
    image2: "./image/5-3.png",
    title_one: "Belajar Pengembangan Aplikasi Android Intermediate",
    desc_one: "Dicoding Certification",
  },
  {
    id: 2,
    image: "./image/6-1.png",
    date: "31 Mei, 2022",
    image1: "./image/6-2.png",
    image2: "./image/6-3.png",
    title_one: "Memulai Pemrograman Dengan Swift",
    desc_one: "Dicoding Certification",
  },
]
export default BlogApi
